<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MemoryIndexer.Sdk\MemoryIndexer.Sdk.csproj" />
    <ProjectReference Include="..\..\tools\SharedLib\SharedLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" />
  </ItemGroup>

</Project>
