using System.Text.Json;
using Microsoft.Extensions.VectorData;

namespace MemoryIndexer.Models;

/// <summary>
/// Represents a single unit of memory stored in the system.
/// Core entity for 3-Tier VCM (Virtual Context Management) architecture.
/// </summary>
/// <remarks>
/// Research reference: research-03.md, research-04.md
/// - Supports Working/Session/User tier placement
/// - Implements Ebbinghaus stability model for forgetting curve
/// - Tracks promotion/demotion history for VCM paging
/// </remarks>
public sealed class MemoryUnit
{
    /// <summary>
    /// Unique identifier for this memory unit.
    /// </summary>
    [VectorStoreKey]
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// The user or tenant this memory belongs to.
    /// Used for multi-tenant isolation.
    /// </summary>
    [VectorStoreData]
    public string UserId { get; set; } = default!;

    /// <summary>
    /// Optional session identifier for grouping related memories.
    /// </summary>
    [VectorStoreData]
    public string? SessionId { get; set; }

    /// <summary>
    /// Optional namespace for sub-user memory isolation.
    /// Used in multi-workspace/multi-tenant scenarios to partition
    /// memories within the same user (e.g., different desks, projects).
    /// Null means no namespace partitioning (default behavior).
    /// </summary>
    [VectorStoreData]
    public string? Namespace { get; set; }

    /// <summary>
    /// Role of the original message sender (user, assistant, system).
    /// Preserved in T0/T1/T2 tiers, typically null for T3 (semantic).
    /// </summary>
    /// <remarks>
    /// Design: Hybrid role handling per cognitive science model.
    /// - Episodic memory (T0-T2): Role preserved for source attribution
    /// - Semantic memory (T3): Role abstracted away (facts only)
    /// </remarks>
    [VectorStoreData]
    public string? Role { get; set; }

    /// <summary>
    /// The actual content of the memory.
    /// </summary>
    [VectorStoreData]
    public string Content { get; set; } = default!;

    /// <summary>
    /// Vector embedding of the content for semantic search.
    /// Dimensions based on BGE-M3 (1024) or configurable.
    /// </summary>
    [VectorStoreVector(Dimensions: 1024)]
    public ReadOnlyMemory<float>? Embedding { get; set; }

    /// <summary>
    /// When this memory was originally created.
    /// </summary>
    [VectorStoreData]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When this memory was last updated.
    /// </summary>
    [VectorStoreData]
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When this memory was last accessed (retrieved).
    /// Used for recency scoring and Ebbinghaus forgetting curve.
    /// </summary>
    [VectorStoreData]
    public DateTime? LastAccessedAt { get; set; }

    /// <summary>
    /// LLM-assigned importance score (0.0 to 1.0).
    /// Based on Generative Agents poignancy rating.
    /// </summary>
    [VectorStoreData]
    public float ImportanceScore { get; set; } = 0.5f;

    /// <summary>
    /// Number of times this memory has been retrieved.
    /// Used for access frequency scoring: log(1 + access_count).
    /// Contributes to Stability calculation via Spacing Effect.
    /// </summary>
    [VectorStoreData]
    public int AccessCount { get; set; }

    /// <summary>
    /// The type of memory (episodic, semantic, procedural, fact).
    /// Based on Tulving's memory classification.
    /// </summary>
    [VectorStoreData]
    public MemoryType Type { get; set; } = MemoryType.Episodic;

    /// <summary>
    /// Current storage tier (Buffer, Short, Long, Archive).
    /// Determines access latency and persistence behavior.
    /// </summary>
    /// <remarks>
    /// BREAKING CHANGE (v0.4.x): Tier enum renamed to Tier.
    /// Values renamed: Sensory→Buffer, Working→Short, Episodic→Long, Semantic→Archive.
    /// Design reference: docs/DESIGN_V0.4.md Section 4 "Tier Axis"
    /// </remarks>
    [VectorStoreData]
    public Tier Tier { get; set; } = Tier.Short;

    /// <summary>
    /// NEW (Phase 32): Memory scope dimension (Turn, Topic, Session, User).
    /// Orthogonal to Type and Tier - defines the "reach" of a memory.
    /// </summary>
    /// <remarks>
    /// Design reference: docs/DESIGN_V0.4.md Section 2.1 "Scope Dimension"
    /// - Turn: Single turn buffer (internal only)
    /// - Topic: Current topic context (internal only)
    /// - Session: Current conversation session (API exposed)
    /// - User: Cross-session persistent (API exposed)
    /// </remarks>
    [VectorStoreData]
    public Scope Scope { get; set; } = Scope.Session;

    /// <summary>
    /// NEW (Phase 32): Optional topic identifier for topic-scoped memories.
    /// Auto-generated by topic detection (Phase 36.1).
    /// Null for Turn/Session/User scopes that don't belong to a specific topic.
    /// </summary>
    [VectorStoreData]
    public string? TopicId { get; set; }

    /// <summary>
    /// NEW (Phase 32): Confidence level for this memory (0.0 to 1.0).
    /// Used for User-scope promotion threshold (confidence >= 0.8).
    /// Different from ConfidenceScore which is for extracted facts.
    /// </summary>
    /// <remarks>
    /// Confidence represents how certain we are this memory is accurate and valuable.
    /// Increases via: explicit user confirmation, repeated activation, cross-validation.
    /// Promotion to User scope requires: Confidence >= 0.8 AND ConfirmCount >= 3.
    /// </remarks>
    [VectorStoreData]
    public float Confidence { get; set; } = 0.5f;

    /// <summary>
    /// NEW (Phase 32): Number of times this memory has been explicitly confirmed by user.
    /// Used for User-scope promotion threshold (confirmCount >= 3).
    /// </summary>
    /// <remarks>
    /// ConfirmCount tracks explicit user validations (e.g., "yes, that's correct").
    /// Different from AccessCount which tracks retrieval frequency.
    /// Promotion to User scope requires: Confidence >= 0.8 AND ConfirmCount >= 3.
    /// </remarks>
    [VectorStoreData]
    public int ConfirmCount { get; set; }

    /// <summary>
    /// NEW (Phase 32): Number of times this memory has been activated in context.
    /// Used for importance scoring and Tier promotion decisions.
    /// </summary>
    /// <remarks>
    /// ActivationCount tracks usage in active context (not just retrieval).
    /// Different from AccessCount which tracks all retrievals.
    /// ActivationCount is a subset of AccessCount (activation implies access).
    /// Used by DomainProfile.ShouldPromote() for tier promotion logic.
    /// </remarks>
    [VectorStoreData]
    public int ActivationCount { get; set; }

    /// <summary>
    /// Memory stability level for forgetting curve calculation.
    /// Higher stability = longer retention without reinforcement.
    /// </summary>
    /// <remarks>
    /// Research reference: intentional-forgetting-mechanisms.md
    /// Formula: R = e^(-t/S), where S is derived from this value.
    /// </remarks>
    [VectorStoreData]
    public MemoryStability Stability { get; set; } = MemoryStability.Volatile;

    /// <summary>
    /// Calculated retention score based on Ebbinghaus curve (0.0 to 1.0).
    /// Updated during access and periodic consolidation.
    /// </summary>
    [VectorStoreData]
    public float RetentionScore { get; set; } = 1.0f;

    /// <summary>
    /// SHA256 hash of the content for duplicate detection.
    /// </summary>
    [VectorStoreData]
    public string? ContentHash { get; set; }

    /// <summary>
    /// Topic labels extracted from the content.
    /// Null when no topics have been extracted (saves memory allocation).
    /// </summary>
    [VectorStoreData]
    public List<string>? Topics { get; set; }

    /// <summary>
    /// Named entities extracted from the content.
    /// Null when no entities have been extracted (saves memory allocation).
    /// </summary>
    [VectorStoreData]
    public List<string>? Entities { get; set; }

    /// <summary>
    /// Additional metadata stored as key-value pairs.
    /// Null when no metadata is present (saves memory allocation).
    /// </summary>
    [VectorStoreData]
    public Dictionary<string, string>? Metadata { get; set; }

    /// <summary>
    /// Soft delete flag.
    /// </summary>
    [VectorStoreData]
    public bool IsDeleted { get; set; }

    /// <summary>
    /// Lock flag to prevent automatic modification/deletion.
    /// Used for system prompts and core facts.
    /// </summary>
    /// <remarks>
    /// Research reference: research-04.md "Lock primitive"
    /// </remarks>
    [VectorStoreData]
    public bool IsLocked { get; set; }

    /// <summary>
    /// Expiration timestamp for TTL-based cleanup.
    /// Null means no expiration.
    /// </summary>
    [VectorStoreData]
    public DateTime? ExpiresAt { get; set; }

    /// <summary>
    /// ID of the memory this one supersedes (for fact updates).
    /// Creates a chain for temporal knowledge tracking.
    /// </summary>
    [VectorStoreData]
    public Guid? SupersedesId { get; set; }

    /// <summary>
    /// LLM-assigned confidence score for extracted facts (0.0 to 1.0).
    /// </summary>
    /// <remarks>
    /// Research reference: FACT_EXTRACTION_KNOWLEDGE_GRAPH_RESEARCH.md
    /// </remarks>
    [VectorStoreData]
    public float? ConfidenceScore { get; set; }

    /// <summary>
    /// Records an access to this memory, updating LastAccessedAt, AccessCount, and Stability.
    /// Implements Spacing Effect: repeated access increases stability.
    /// </summary>
    public void RecordAccess()
    {
        LastAccessedAt = DateTime.UtcNow;
        AccessCount++;

        // Spacing Effect: access count thresholds for stability upgrade
        // Research reference: research-03.md "Spacing Effect"
        Stability = AccessCount switch
        {
            >= 10 when Stability < MemoryStability.Consolidated => MemoryStability.Consolidated,
            >= 5 when Stability < MemoryStability.Stable => MemoryStability.Stable,
            >= 2 when Stability < MemoryStability.Stabilizing => MemoryStability.Stabilizing,
            _ => Stability
        };

        // Reset retention score on access (memory reinforcement)
        RetentionScore = 1.0f;
    }

    /// <summary>
    /// Marks this memory as updated.
    /// </summary>
    public void MarkUpdated()
    {
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Calculates current retention using Ebbinghaus forgetting curve.
    /// R = e^(-t/S), where t = time since last access, S = stability factor.
    /// </summary>
    /// <param name="referenceTime">Time to calculate retention for (defaults to now).</param>
    /// <returns>Retention score between 0.0 and 1.0.</returns>
    public float CalculateRetention(DateTime? referenceTime = null)
    {
        var now = referenceTime ?? DateTime.UtcNow;
        var lastAccess = LastAccessedAt ?? CreatedAt;
        var daysSinceAccess = (now - lastAccess).TotalDays;

        // Stability factor based on stability level
        // Research reference: intentional-forgetting-mechanisms.md
        var stabilityFactor = Stability switch
        {
            MemoryStability.Volatile => 1.0,      // ~1 day half-life
            MemoryStability.Stabilizing => 7.0,   // ~7 days half-life
            MemoryStability.Stable => 30.0,       // ~30 days half-life
            MemoryStability.Consolidated => 365.0, // ~1 year half-life
            MemoryStability.Permanent => double.MaxValue, // No decay
            _ => 1.0
        };

        // Ebbinghaus formula: R = e^(-t/S)
        var retention = (float)Math.Exp(-daysSinceAccess / stabilityFactor);
        return Math.Clamp(retention, 0f, 1f);
    }

    /// <summary>
    /// Checks if this memory should be considered for eviction.
    /// </summary>
    /// <param name="retentionThreshold">Minimum retention to avoid eviction.</param>
    /// <returns>True if memory is a candidate for eviction.</returns>
    public bool ShouldEvict(float retentionThreshold = 0.1f)
    {
        if (IsLocked) return false;
        if (Stability == MemoryStability.Permanent) return false;
        return CalculateRetention() < retentionThreshold;
    }

    /// <summary>
    /// Sets a typed metadata value with JSON serialization.
    /// Phase 28: Structured metadata API for type-safe storage.
    /// </summary>
    /// <typeparam name="T">Type of the metadata value.</typeparam>
    /// <param name="key">Metadata key.</param>
    /// <param name="value">Metadata value to serialize.</param>
    public void SetMetadata<T>(string key, T value)
    {
        Metadata ??= new Dictionary<string, string>();
        Metadata[key] = JsonSerializer.Serialize(value);
    }

    /// <summary>
    /// Gets a typed metadata value with JSON deserialization.
    /// Phase 28: Structured metadata API for type-safe retrieval.
    /// </summary>
    /// <typeparam name="T">Type of the metadata value.</typeparam>
    /// <param name="key">Metadata key.</param>
    /// <returns>Deserialized metadata value, or default(T) if not found.</returns>
    public T? GetMetadata<T>(string key)
    {
        if (Metadata is null || !Metadata.TryGetValue(key, out var json))
            return default;
        return JsonSerializer.Deserialize<T>(json);
    }

    /// <summary>
    /// Tries to get a typed metadata value with JSON deserialization.
    /// Phase 28: Structured metadata API for safe type-safe retrieval.
    /// </summary>
    /// <typeparam name="T">Type of the metadata value.</typeparam>
    /// <param name="key">Metadata key.</param>
    /// <param name="value">Deserialized metadata value if found.</param>
    /// <returns>True if metadata exists and was deserialized successfully.</returns>
    public bool TryGetMetadata<T>(string key, out T? value)
    {
        if (Metadata is null || !Metadata.TryGetValue(key, out var json))
        {
            value = default;
            return false;
        }
        try
        {
            value = JsonSerializer.Deserialize<T>(json);
            return true;
        }
        catch
        {
            value = default;
            return false;
        }
    }
}
