using System.Text;
using Microsoft.Extensions.Logging;
using TwentyQuestionsGame.Game;
using TwentyQuestionsGame.LLM;
using TwentyQuestionsGame.ToolCall;

namespace TwentyQuestionsGame.Agents;

/// <summary>
/// Alpha agent - the QuizMaster who answers questions.
/// Secret is generated by LLM on first turn and stored in memory.
/// </summary>
public sealed class AlphaAgent(
    LlmClient llmClient,
    ToolCallParser parser,
    ToolCallExecutor executor,
    ILogger<AlphaAgent> logger) : AgentBase(llmClient, parser, executor, logger)
{
    private string _systemPromptTemplate = "";

    protected override string UserId => GameConfiguration.AlphaUserId;
    protected override string SessionId => GameConfiguration.AlphaSessionId;

    public void Initialize(string systemPromptTemplate)
    {
        _systemPromptTemplate = systemPromptTemplate;
    }

    /// <summary>
    /// Answers Beta's question and returns structured response.
    /// On Round 1, Alpha also chooses and stores the secret.
    /// For Round 2+, automatically pre-recalls the secret and injects it into the prompt.
    /// </summary>
    public async Task<AlphaAnswerResult> AnswerAsync(
        string betaQuestion,
        int currentRound,
        CancellationToken ct = default)
    {
        var systemPrompt = _systemPromptTemplate.Replace("{{ROUND}}", currentRound.ToString());

        // For rounds 2+, pre-recall the secret and inject it into the user message
        var userMessage = betaQuestion;
        if (currentRound > 1)
        {
            var recalledSecret = await RecallSecretAsync(ct);
            if (!string.IsNullOrEmpty(recalledSecret))
            {
                var messageBuilder = new StringBuilder();
                messageBuilder.AppendLine("=== YOUR SECRET (RECALLED FROM MEMORY) ===");
                messageBuilder.AppendLine(recalledSecret);
                messageBuilder.AppendLine("=== END OF SECRET ===\n");
                messageBuilder.AppendLine($"Beta's question: {betaQuestion}");
                messageBuilder.AppendLine("\nUse the VERIFICATION chain to answer accurately based on YOUR SECRET above.");
                userMessage = messageBuilder.ToString();
            }
        }

        var response = await ProcessWithToolsAsync(systemPrompt, userMessage, ct);

        // Try to parse JSON response
        var parsed = AlphaResponse.TryParse(response.RawContent);

        if (parsed != null)
        {
            return new AlphaAnswerResult
            {
                Answer = parsed.Answer,
                IsGuess = parsed.IsGuess,
                GuessCorrect = parsed.GuessCorrect,  // Trust LLM's judgment
                RawResponse = response.RawContent,
                PromptTokens = response.PromptTokens,
                CompletionTokens = response.CompletionTokens,
                LatencyMs = response.LatencyMs
            };
        }

        // Fallback: extract answer from raw content
        var normalizedAnswer = AlphaResponse.NormalizeAnswer(response.FinalOutput);

        return new AlphaAnswerResult
        {
            Answer = normalizedAnswer,
            IsGuess = false,
            GuessCorrect = false,
            RawResponse = response.RawContent,
            PromptTokens = response.PromptTokens,
            CompletionTokens = response.CompletionTokens,
            LatencyMs = response.LatencyMs
        };
    }

    /// <summary>
    /// Pre-recalls Alpha's secret from memory to ensure consistent answers.
    /// </summary>
    private async Task<string?> RecallSecretAsync(CancellationToken ct)
    {
        try
        {
            var toolCall = new ParsedToolCall(
                "memory_recall",
                new Dictionary<string, string>
                {
                    ["query"] = "MY_SECRET",
                    ["limit"] = "5"
                },
                "memory_recall(query=\"MY_SECRET\", limit=5)");

            var result = await executor.ExecuteAsync(toolCall, UserId, SessionId, ct);

            if (result.IsSuccess && !string.IsNullOrEmpty(result.Data) && !result.Data.Contains("No relevant memories"))
            {
                return result.Data;
            }
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Failed to pre-recall Alpha's secret");
        }

        return null;
    }
}

/// <summary>
/// Result of Alpha answering a question.
/// </summary>
public sealed record AlphaAnswerResult
{
    public string Answer { get; init; } = "No";
    public bool IsGuess { get; init; }
    public bool GuessCorrect { get; init; }
    public string RawResponse { get; init; } = "";
    public int PromptTokens { get; init; }
    public int CompletionTokens { get; init; }
    public long LatencyMs { get; init; }
}
